name: 🐧 Linux Builds
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      target_arch:
        required: false
        type: string
        default: x86_64
      prefix_arch:
        required: false
        type: string
        default: linux64

# Global Settings
# SCONS_CACHE for windows must be set in the build environment
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: master
  SCONS_CACHE_MSVC_CONFIG: true

concurrency:
  cancel-in-progress: true
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-linux-${{ inputs.target }}

jobs:
  build-linux:
    runs-on: "ubuntu-20.04"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux build - ${{ inputs.target }} (${{ inputs.target_arch }})
            cache-name: Linux
            target: ${{ inputs.target }}
            prefix_arch: ${{ inputs.prefix_arch }}
            target_arch: ${{ inputs.target_arch }}
            # Skip debug symbols, they're way too big with MSVC.
            sconsflags: debug_symbols=no
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # - name: Download ffmpeg
      #   run: |
      #     wget https://github.com/EIRTeam/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-lgpl-godot.tar.xz
      #     tar xvf ffmpeg-master-latest-linux64-lgpl-godot.tar.xz

      - name: Install deps
        shell: sh
        run: |
          sudo apt update
          sudo apt -y install clang llvm lld libclang-11-dev libstdc++6 nasm autoconf \
                      automake libtool pkg-config curl git doxygen rapidjson-dev cmake gperf \
                      groff texinfo yasm bison autogen wget meson ninja-build

      - name: Cache ffmpeg build
        id: cache-ffmpeg-linux
        uses: actions/cache@v4
        with:
          path: thirdparty/ffmpeg
          key: ${{ runner.os }}-ffmpeg-linux-${{ matrix.target_arch }}-${{ hashFiles('./ffmpeg-kit/**') }}

      - name: Make ffmpeg
        if: steps.cache-ffmpeg-linux.outputs.cache-hit != 'true'
        shell: sh
        env:
          PLATFORM: linux
          TARGET_ARCH: ${{ matrix.target_arch }}
        run: |
          make ffmpeg

      - name: show build.log
        if: always()
        run: |
          cat ./ffmpeg-kit/build.log

      - name: Setup python and scons
        uses: ./.github/actions/deps

      - name: Compilation
        uses: ./.github/actions/build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }}
          ffmpeg-path: "../thirdparty/ffmpeg/linux/${{ matrix.prefix_arch }}"
          platform: linux
          target: ${{ matrix.target }}
          tests: ${{ matrix.tests }}
      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: artifacts
          path: ./gdextension_build/build/*
